Pull Request #2; Added headline and mobile skeleton
desorgui/my-portfolio-microverse pull request #2
Opened 2022-04-21 17:15 UTC by desorgui

The added headline and mobile skeleton for this project.

2022-04-21 18:28 UTC, danmainah requested changes
Hi @desorgui, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used


# Required Changes ♻️

- [x]  Kindly make sure your pull request message is descriptive currently it's too short and doesn't describe fully what you did in this milestone.

_Check the comments under the review._

## Optional suggestions

- [x] Kindly ensure your readme file is more descriptive you can add the Getting Started section.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me using @danmainah in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 18:28 UTC, danmainah commented on index.html
> +			</div>
- [ ] Kindly make sure your image is a background image using CSS background property currently you are using `<img>` tag, also ensure your design matches the given design.

2022-04-21 18:28 UTC, danmainah commented on style.css
> +@media screen and (max-width: 375px) {
- [ ] Kindly resize your media query breakpoint, currently it's too small ,check out [this article](https://www.freecodecamp.org/news/css-media-queries-breakpoints-media-types-standard-resolutions-and-more/) to learn common breakpoint

2022-04-21 22:25 UTC, desorgui commented
Hi @danmainah , thanks for reviewing my code, I've made some changes and I've already submitted some another time I don't know if you have any other requires change

2022-04-21 23:05 UTC, Div685 requested changes
# :yellow_circle: Almost There! :muscle: 
Hi, **@desorgui**,  I'm Divyesh your reviewer for this PR :man_technologist: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
:heavy_check_mark: Linters are passing
:heavy_check_mark: Descriptive PR Title

 ## Required Changes ♻️
**_Check the comments under the review._**


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Code review by **Divyesh Patel**

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.)_

------

>**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

>_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-21 23:05 UTC, Div685 commented on index.html
> +						<img
- [x] [REQUIRED] I think, It would be better if you remove the white background (border) from the hamburger icon. If you decide to use an image as an icon, please make sure it matches the design in Figma. The white border makes UI looks ugly. 
> Hint: You can use icons from [font-awesome](https://fontawesome.com/icons) though it's not a requirement.

2022-04-21 23:05 UTC, Div685 commented on index.html
> +			<div class="image"></div>
- [x] [REQUIRED] Please, It's always a good practice to double-check your web page on the browser. Your background image is overlapping the width of the page. Please always make sure you don't show a horizontal scroll bar unless it's absolutely required.
![Screenshot_3CR](https://user-images.githubusercontent.com/24191094/164561196-b0679b02-22c3-410c-82dc-f1e5fe798576.png)
>- [ ] Hint: [OPTIONAL] you can use this background image on the section tag `<section class="headline">` to make your work easy.

2022-04-21 23:05 UTC, Div685 commented on index.html
> +				<div class="nav-button">
- [x] [REQUIRED] Kindly wrap the hamburger Icon with the `nav` tag for semantic purposes. It's the best practice to use semantic elements for better readability and easier to maintain. you can either replace the div with a nav tag or create a nav tag outside the div tag.

2022-04-21 23:05 UTC, Div685 commented on index.html
> +								alt=""
- [x] [Optional] It's a good practice to add text in the `alt` for better SEO purposes. for example: `alt="facebook"`

2022-04-22 16:48 UTC, JuliCarracedo approved these changes
# Status: Approved ✔️
Hi @desorgui , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 20:52 UTC, merged