Implement Desktop version of contact form and footer section
desorgui/my-portfolio-microverse pull request #7
Opened 2022-05-07 16:38 UTC by desorgui

## What?
Implementation of the desktop version of the contact form and footer

## Why?
These changes complete the project requirements.

## How?
I used Html and CSS (Grid and Flexbox) to be able to place each element of my project, and also change the display for mobile
## Testing?
I've added Linter for testing all new CSS codes.

## Anything Else?
I used [template 2](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27) of the Microverse students' projects to implement my portfolio

2022-05-07 18:05 UTC, gemmen29 requested changes
Hi @desorgui, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 18:05 UTC, gemmen29 commented on style.css
- [ ] Kindly use a min-width media query for the desktop version from any point between `768px` to `1440px` as this project is the recommended width for the desktop version and this project is mobile-first.

for example:
```
@media screen and (min-width: 1080px) { // any value between 768 and 1440 is ok.
/*
.
.
*/
}

```

2022-05-07 18:05 UTC, gemmen29 commented on index.html
> +			<h1 class="section-title font-crete">My Recents works</h1>
- [ ] Kindly add some spacing on the left and right in the `My Recents works` section `mobile-version` to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/167266194-50ea247d-f1a2-4862-903b-a7501497193b.png) |![image](https://user-images.githubusercontent.com/24703171/167266157-ceb7ac82-d5a3-4625-85f5-fccea5b52ee4.png) |

2022-05-07 18:05 UTC, gemmen29 commented on index.html
> +				<h1 class="font-crete">About me</h1>
- [ ] Kindly add some spacing between the `about me` section and the white horizontal line in `desktop-version` to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/167266325-0647f2da-3e91-40bf-a2f3-573cdae0d105.png) | ![image](https://user-images.githubusercontent.com/24703171/167266416-b63476fa-9978-4a16-8ac7-8801c19bae80.png) |

2022-05-07 23:11 UTC, gtekle requested changes
Hi @desorgui :wave: , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![dog-pug](https://user-images.githubusercontent.com/44057863/167274885-fb969a68-6e8b-4fcd-8916-335204c325a9.gif)

 ## Highlights
:heavy_check_mark: Professional Readme
:heavy_check_mark: Descriptive pull request summary

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ Optional ] Kindly update the left alignment of the paragraph in the contact-me section as in the figma design. 
![contact-me-parag-left-align-impl](https://user-images.githubusercontent.com/44057863/167274827-33bdaa11-785f-4b16-a073-44debc454856.png)

- [ Optional ] Kindly left align (Flex start) on the Desktop version for the Skills section.
#### Figma
![skills-section-left-alignment-figma](https://user-images.githubusercontent.com/44057863/167274812-9923744c-2f26-4664-8970-3850fb4ca707.png)
#### Impl
![skills-section-left-alignment-impl](https://user-images.githubusercontent.com/44057863/167274823-f182dd35-8d22-4a5f-9ab9-d84d5f5d4ad8.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 23:11 UTC, gtekle commented on style.css
>    body {
- [ ] You should use `min-width: 768px;` as the previous reviewer suggested and as per the project requirement.
![desktop-vers-768-instruct](https://user-images.githubusercontent.com/44057863/167274739-284d7322-4f94-43e7-aecf-c28f57a7755c.png)

2022-05-08 02:44 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey  @desorgui 😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

#### Optional
Please remove the extra spaces from the sides.
<img width="1440" alt="Screen Shot 2022-05-08 at 7 43 26 AM" src="https://user-images.githubusercontent.com/83048208/167279500-8b5a1fbf-d2a7-49ec-9ad0-ecebc7052a01.png">


# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-08 03:20 UTC, merged